-
  -
    description: the north west chamber
    exits:
      - E
      - S
    items:
      - shovel
      - key
  -
    description: the north east chamber
    exits:
      - W
      - S
-
  -
    description: the south west chamber
    exits:
      - N
    items:
      - chest
  -
    description: the south east chamber
    exits:
      - N
