-
  -
    description: north west
    exits:
      - E
      - S
  -
    description: north east
    exits:
      - W
      - S
-
  -
    description: south west
    exits:
      - N
  -
    description: south east
    exits:
      - N
