- id: usidore
  description: a wizard
  words:
    - I am Usidore, Wizard of the 12th Realm of Ephysiyies,
    - Master of Light and Shadow,
    - Manipulator of Magical Delights,
    - Devourer of Chaos,
    - Champion of the Great Halls of Terr'akkas.
    - The elves know me as Fi’ang Yalok,
    - the dwarves know me as Zoenen Hoogstandjes,
    - and I am known in the Northeast as Gaismunenas Meistar,
    - and there may be other secret names which you do not know yet

- id: chunt
  description: a talking badger
  words:
    - Chunt's up with that?
